id: AB373493D
title: 'Padma’s Melodious Song: A Prayer for the Long Life of the Fourth in the Succession
  of Lotus-Tongued Jamchen Tai Situ Incarnations'
type: translation
pechas:
- IA99B30A8
- I20EF4826
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:15:23.756738
  last_modified_at: 2023-01-04 12:15:23.756743
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IA99B30A8/9E44: A4A9
  I20EF4826/21E9: A4A9
